title: Portfolio
author: Ben Bethke
email: ben.bethke@att.net
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Ben's online portfolio to display resume, projects, and achievements.

# social links
linkedin_username: benjamin-bethke
github_username:  benbethke

show_excerpts: true # set to false to remove excerpts on the homepage
